name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["mint-choc-chip-skyblade/1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Discord ID / GitHub Username
      description: How can we get in touch with you if we need more info?
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to happen?
      description: Tell us any details about what you expected should happen.
      placeholder: I expected picking up a blue rupee to give me 5 rupees!
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What actually happened?
      description: Tell us any details about what actually happened. Please include screenshots or videos, if possible.
      placeholder: I didn't get any rupees!
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: Which OS did you run the randomizer on?
      options:
        - Windows
        - MacOS (Apple Silicon)
        - MacOS (Intel)
        - Linux
      default: 0
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where did you play the randomizer?
      options:
        - Console
        - Emulator
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Randomizer Version
      description: Which randomizer version were you using when you experienced this bug?
      placeholder: "1.0"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this bug, you agree to follow our [Code of Conduct](https://github.com/mint-choc-chip-skyblade/sshd-rando?tab=coc-ov-file#readme). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
