name: Release

# automatically run on version tag
on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      env: "Production"
  release:
    runs-on: ubuntu-latest

    needs: [build]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Version
        uses: SebRollen/toml-action@v1.2.0
        id: read_toml
        with:
          file: "constants/randoconstants.py"
          field: "VERSION"
      
      - name: Download all Artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.run_id }}
          github-token: ${{ github.token }}
          merge-multiple: true
  
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./Skyward Sword HD Randomizer 1.0 Pre-release2.exe
            ./Skyward Sword HD Randomizer v1.0 Pre-release2 (linux).tar
            ./Skyward Sword HD Randomizer v1.0 Pre-release2 (macos_apple_silicon).tar
            ./Skyward Sword HD Randomizer v1.0 Pre-release2 (macos_intel).tar
